### ISSUE TITLE
some https put requests error when no data is included with request

### ISSUE THREAD

**Issue by WestleyArgentum** [JuliaWeb/Requests.jl#30] opened 2014-07-24 15:14 UTC
@garborg and I have been playing with GitHub.jl and we noticed that put requests to the GitHub API seem fail with the below error unless data is passed along in the request.

```julia
ERROR: stream is closed or unusable
 in check_open at stream.jl:294
 in write at stream.jl:729
 in close at /Users/westley/.julia/v0.3/GnuTLS/src/GnuTLS.jl:96
 in on_message_complete at /Users/westley/.julia/v0.3/Requests/src/Requests.jl:151
 in http_parser_execute at /Users/westley/.julia/v0.3/HttpParser/src/HttpParser.jl:106
 in process_response at /Users/westley/.julia/v0.3/Requests/src/Requests.jl:228
 in do_request at /Users/westley/.julia/v0.3/Requests/src/Requests.jl:562
 in put at /Users/westley/.julia/v0.3/Requests/src/Requests.jl:576
 in star at /Users/westley/.julia/v0.3/GitHub/src/starring.jl:54
 in star at /Users/westley/.julia/v0.3/GitHub/src/starring.jl:45
```

Probing further, we've found that making the request using [Postman](https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm?hl=en) works just fine (to test, try making a PUT request to `https://api.github.com/user/starred/$YOUR_USER/github.jl` with the `"Authorization"` header set to `"token ***YOUR_TOKEN***"`).

That leads me to believe the problem is somewhere in Requests.jl or the underlying http libraries. To repo using just Reqests.jl:

```julia
# will work just fine
put("https://api.github.com/user/starred/$YOUR_USER/github.jl"; data = "{}", headers = {"Authorization"=>"token ***YOUR_TOKEN***"})

# will hang and eventually error
put("https://api.github.com/user/starred/$YOUR_USER/github.jl"; headers = {"Authorization"=>"token ***YOUR_TOKEN***"})
```

**Comment by sbromberger** [comment] 2015-02-16 17:14
This may be fixed in the "ird/tempfix" branch of GnuTLS - would you mind testing?

**Comment by malmaud** [comment] 2015-08-27 05:30
I can't reproduce - perhaps a newer version of GnuTLS did indeed fit it. Please reopen if it still happens.

**Closed by malmaud** 2015-08-27 05:30 UTC
