### ISSUE TITLE
get() failing

### ISSUE THREAD

**Issue by ianshmean** [JuliaWeb/Requests.jl#103] opened 2016-02-29 10:14 UTC
URLs that work on 0.3.12 are failing in 0.4.2.
The kernel just hangs with no response:

```
using Requests
println(get("https://google.com"))
```

- HttpParser                    0.1.1+             master
- JSON                          0.5.0
- LibBSON                       0.2.0+             master
- MbedTLS                       0.2.1+             master
- Requests                      0.3.5              master

**Comment by rohitvarkey** [comment] 2016-02-29 22:27
I was able to replicate this error on `0.4.2` and `0.4.3` and todays nightly. Doing a `Pkg.free("MbedTLS")` fixes this for me.

https://github.com/JuliaWeb/MbedTLS.jl/pull/30 seems to be the cause since it is the only [change](https://github.com/JuliaWeb/MbedTLS.jl/compare/v0.2.1...master) from the released version of MbedTLS. (0.2.1).

cc: @vtjnash

**Comment by malmaud** [comment] 2016-03-01 18:05
I can confirm this. I can look into it in day or so if @vtjnash doesn't beat me to it.

**Comment by malmaud** [comment] 2016-03-01 21:55
Fixed by https://github.com/JuliaWeb/MbedTLS.jl/pull/32

**Closed** 2016-03-01 22:11 UTC
