### ISSUE TITLE
signal (10): Bus error: 10 unknown function

### ISSUE THREAD

**Issue by dyzdyz010** [JuliaWeb/Requests.jl#113] opened 2016-04-25 02:06 UTC
This happens only when server returns specific value in an http request:

```
signal (10): Bus error: 10
unknown function (ip: 0x10a429270)
[1]    51669 bus error  julia test/runtests.jl
```

In a QRCode login procedure

pre-request
```
GET https://ssl.ptlogin2.qq.com/ptqrshow?appid=501004106&e=0&l=M&s=5&d=72&v=4&t=0.4139144900254905

HTTP/1.1 200 OK
Server: nginx/1.7.9
Date: Sun, 24 Apr 2016 05:47:30 GMT
Content-Type: image/png
Content-Length: 486
Connection: close
Accept-Ranges: bytes
Pragma: No-cache
P3P: CP="CAO PSA OUR"
Set-Cookie: qrsig=Vn8VjX0L7KDxOPb*xb86DpaA7Z*pnILlIxWQ3IroLrEj*c2rQ0*YibXy39RfsMVN; PATH=/; DOMAIN=ptlogin2.qq.com;

PNG

png body
```

And in-code request: `https://ssl.ptlogin2.qq.com/ptqrlogin?webqq_type=10&remember_uin=1&login2qq=1&aid=501004106&u1=http%3A%2F%2Fw.qq.com%2Fproxy.html%3Flogin2qq%3D1%26webqq_type%3D10&ptredirect=0&ptlang=2052&daid=164&from_ui=1&pttype=1&dumy=&fp=loginerroralert&action=0-0-136435&mibao_css=m_webqq&t=undefined&g=1&js_type=0&js_ver=10139&login_sig=&pt_randsalt=0`

```
GET /ptqrlogin?webqq_type=10&remember_uin=1&login2qq=1&aid=501004106&u1=http%3A%2F%2Fw.qq.com%2Fproxy.html%3Flogin2qq%3D1%26webqq_type%3D10&ptredirect=0&ptlang=2052&daid=164&from_ui=1&pttype=1&dumy=&fp=loginerroralert&action=0-0-136435&mibao_css=m_webqq&t=undefined&g=1&js_type=0&js_ver=10139&login_sig=&pt_randsalt=0 HTTP/1.1
Cookie: qrsig=Vn8VjX0L7KDxOPb*xb86DpaA7Z*pnILlIxWQ3IroLrEj*c2rQ0*YibXy39RfsMVN
Host: ssl.ptlogin2.qq.com
Connection: close
User-Agent: Paw/2.3.3 (Macintosh; OS X/10.11.4) GCDHTTPRequest
```

This should be responded with something like this:
```
ptuiCB('0','0','**A URL HERE**','0','登录成功！', 'XXX');
```

However the function crashed with output:
```
signal (10): Bus error: 10
unknown function (ip: 0x10a429270)
[1]    51669 bus error  julia test/runtests.jl
```

My code below:

```
query_params = Dict(
    "webqq_type" => 10,
    "remember_uin" => 1,
    "login2qq" => 1,
    "aid" => 501004106,
    "u1" => "http://w.qq.com/proxy.html?login2qq=1&webqq_type=10",
    "ptredirect" => 0,
    "ptlang" => 2052,
    "from_ui" => 1,
    "pttype" => 1,
    "dumy" => "",
    "fp" => "loginerroralert",
    "action" => "0-0-136435",
    "mibao_css" => "m_webqq",
    "t" => "undefined",
    "g" => 1,
    "js_type" => 0,
    "js_ver" => 10139,
    "login_sig" => "",
    "pt_randsalt" => 0
    )
    url = "https://ssl.ptlogin2.qq.com/ptqrlogin"

    r = get(url, query = query_params, cookies = cookies, allow_redirects=false)
```
`cookies ` is retrieved from the first response.

**Comment by malmaud** [comment] 2016-05-10 15:18
I suspect this is caused by the same issue as https://github.com/JuliaWeb/Requests.jl/issues/115, so I'll close it as a duplicate for now. But if it turns out it isn't, I'll reopen it.

**Closed by malmaud** 2016-05-10 15:18 UTC
